### ISSUE TITLE
Bijdrage

### ISSUE THREAD

**Issue by arbakker** [codefornl/coronamap-nl#1]
Ha, ik heb afgelopen weekend een kaartje gemaakt, misschien kan er eea hergebruikt worden, zie https://arbakker.github.io/corona-map-nl/ (bevat ook een linkje naar de repo, in de attribution string). De kaart maakt gebruik van de leaflet cluster marker [plugin](https://github.com/Leaflet/Leaflet.markercluster) en wordt dagelijks automatisch ververst (door de site van RIVM te scrapen). Ben bereid om te helpen :)

**Comment by jgroenen** [comment]
Hoi Anton, mooi om te horen. Zit je al in de Slack? https://doemee.codefor.nl

**Comment by arbakker** [comment]
Top, heb me aangemeld 👍
